services:
  db:
    image: postgres:15-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app   # This syncs your code instantly without rebuilding
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app  # This syncs your React code instantly
      - /app/node_modules # Prevents local modules from overriding Docker's
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pg_data: