# Generated by Django 5.2.17 on 2026-10-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_notebook_remove_documento_cuaderno_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tramos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
